version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: chainmetrics
      POSTGRES_PASSWORD: chainmetrics
      POSTGRES_DB: chainmetrics
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_USER=chainmetrics
      - DB_PASSWORD=chainmetrics
      - DB_NAME=chainmetrics
      - DB_PORT=5432
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8080/api
    depends_on:
      - backend

volumes:
  postgres_data: 